### ISSUE TITLE
Many of the UI Verse Components seems to be inconsistent with our website ui design

### ISSUE THREAD

**Issue by SH20RAJ** [SH20RAJ/rookus#11]
## We should keep the UI color pallets and design consistent

---

- [x] Sudden UI Change will be not good for users 
@Crap1nyk

**Comment by Crap1nyk** [comment]
we can use other components as well including our own built so lets use simple ones

**Comment by Crap1nyk** [comment]
for color pallete whole ui will be redesigned accordingly
