### ISSUE TITLE
Search bar is causing bad user experience for users 

### ISSUE THREAD

**Issue by SH20RAJ** [SH20RAJ/rookus#14]
Search bar is causing bad user experience for slow internet users 

<img width="1470" alt="Screenshot 2024-10-11 at 11 35 11 AM" src="https://github.com/user-attachments/assets/be9a23bf-13de-4b50-980f-de0608ee2857">

**Comment by Crap1nyk** [comment]
we have to render it at the end so its fine remove it or change to a simpler search

**Comment by Crap1nyk** [comment]
we can render components at the end for such components and add them again so dont delete them just make a new component and add it there as reference

**Comment by Crap1nyk** [comment]
Issue has been resolved
