### ISSUE TITLE
Error in build time

### ISSUE THREAD

**Issue by SH20RAJ** [SH20RAJ/rookus#15]
<img width="1470" alt="Screenshot 2024-10-11 at 1 24 32 PM" src="https://github.com/user-attachments/assets/be582d2b-37e0-4560-bc6c-0f78fb5fd576">

**Comment by Crap1nyk** [comment]
install dependencies
ask gpt it will give the codes for loading the same

**Comment by Crap1nyk** [comment]
ESLINT ERROR DEPENDENCY CONTROLS

**Comment by SH20RAJ** [comment]
Done

**Comment by Crap1nyk** [comment]
try set up the project again after deleting the whole and install again it will be easier as it will itself install all the dependencies

**Comment by SH20RAJ** [comment]
Try this eslint rule :- https://stackoverflow.com/questions/43177074/how-can-i-fix-this-violation-of-this-react-no-unescaped-entitie-of-an-eslint-r

> and all set 👍

**Comment by SH20RAJ** [comment]
> try set up the project again after deleting the whole and install again it will be easier as it will itself install all the dependencies

It's a common error, and it's resolved now, no need to do this
