### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by SH20RAJ** [SH20RAJ/rookus#3]

**Comment by SH20RAJ** [comment]
Send me the figma link here.... @Crap1nyk

**Comment by SH20RAJ** [comment]
> Send me the figma link here.... @Crap1nyk

I got it https://www.figma.com/design/7QjB6hbyY5f9WaZrv4XWJK/Untitled?node-id=0-1

**Comment by Crap1nyk** [comment]
corrected
