### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by SH20RAJ** [SH20RAJ/rookus#6]
## Upload all images and assets that will be used in the creation of landing page of `rookus.ai`

---

- [x] T Shirt Images (10+)
- [x] Logo
- [x] Dashboard Image
- [x] User Images
- [x] Founder Images

**Comment by Crap1nyk** [comment]
![6e93334a77f08f99d41737fcfa13ed247dfc3f60](https://github.com/user-attachments/assets/ae0bffb4-5ba8-4b85-b280-e1d95c17d31b)
![IMG-20240707-WA0012](https://github.com/user-attachments/assets/3961365b-81bf-4a8b-be74-efcde5983050)
![IMG-20240718-WA0036](https://github.com/user-attachments/assets/e54d5471-646b-4005-8726-89e31ef81ec9)
![IMG-20240723-WA0050](https://github.com/user-attachments/assets/e9478036-0132-4147-b04c-2ebf01c5eb6f)
![IMG-20240802-WA0036](https://github.com/user-attachments/assets/36225896-797b-4437-bca5-c4d41affa0dd)
![IMG-20240811-WA0062](https://github.com/user-attachments/assets/10a16539-b55f-4f54-a7a6-2bb5319a1b54)
![IMG-20240825-WA0001](https://github.com/user-attachments/assets/fd07b7f3-7dd0-4c52-aa54-e6da8eb80b58)
![IMG-20240825-WA0005](https://github.com/user-attachments/assets/b16fff49-caa6-46de-86a4-d4ffb1927301)
![IMG-20240826-WA0024](https://github.com/user-attachments/assets/38cc79de-39e7-489d-ba30-e89425451116)
![IMG-20240826-WA0027](https://github.com/user-attachments/assets/e3f7eef8-d3cc-495d-9d65-96c3ff04a23e)
![IMG-20240907-WA0013](https://github.com/user-attachments/assets/ca5e11fc-0e5f-4b67-ab69-7d4b939b2779)
![IMG-20240907-WA0023](https://github.com/user-attachments/assets/757988e3-b0ef-4f99-80bc-8f0607f1f28c)
![IMG-20240916-WA0007](https://github.com/user-attachments/assets/b9b55d79-4f56-4fc8-bc22-4ddb550e5537)
![IMG-20240924-WA0019](https://github.com/user-attachments/assets/198b68a5-cc53-4e27-80e6-ea3e65872038)
![ic_launcher](https://github.com/user-attachments/assets/7790c6f4-9f4c-4d2b-96cf-2942b5d58a8f)
![WhatsApp Image 2024-07-20 at 13 58 35_d2e288a3](https://github.com/user-attachments/assets/7c5d5bbc-0315-485c-94ce-1e935f241927)
![WhatsApp Image 2024-07-20 at 13 58 36_0ab283fd](https://github.com/user-attachments/assets/143d8506-93bb-4732-86ca-284fd7a972d1)
![WhatsApp Image 2024-07-20 at 13 58 36_263e4821](https://github.com/user-attachments/assets/2baa8d7d-c9ee-48a0-85c2-b3265b6d9b7e)
![nik](https://github.com/user-attachments/assets/edaca8bd-0847-4343-a715-328aed3dfd4c)
![ry](https://github.com/user-attachments/assets/3603b9fd-3128-44b5-a3cd-d7f81407c0f4)
![samina](https://github.com/user-attachments/assets/409ebade-7c0c-4cd7-ba06-c1bad3c117ce)

**Comment by Crap1nyk** [comment]
![Uploading WhatsApp Image 2024-07-02 at 20.36.32_393a624f.jpg…]()

**Comment by Crap1nyk** [comment]
![Uploading WhatsApp Image 2024-07-02 at 20.36.32_393a624f.jpg…]()

**Comment by Crap1nyk** [comment]
![WhatsApp Image 2024-07-02 at 20 36 32_393a624f](https://github.com/user-attachments/assets/4c7a698f-f907-40e9-abf8-33785ae2b9fb)
